applicationset:
  name: gox-stg-console-notification
  namespace: openshift-gitops

clusterSelector:
  matchLabels:
    gox.li9.com/environment: stg

environment:
  name: stg
  valueFiles:
    - values-common.yaml
    - values-stg.yaml
