applicationset:
  name: gox-sbx-console-notification
  namespace: openshift-gitops

source:
  targetRevision: sbx

clusterSelector:
  matchLabels:
    gox.li9.com/environment: sbx

environment:
  name: sbx
  valueFiles:
    - values-common.yaml
    - values-sbx.yaml
