applicationset:
  name: gox-prd-console-notification
  namespace: openshift-gitops

clusterSelector:
  matchLabels:
    gox.li9.com/environment: prd

environment:
  name: prd
  valueFiles:
    - values-common.yaml
    - values-prd.yaml
